Repository iamkanhaiyakumar/ai-content-generator, pull requests merged in 2024-11, with the labels that each got.

#69 Addedvercelconfigfiles
  PROJECT_STRUCTURE.md
  repo_structure.txt
  vercel.json
Labels: level1

#71 Feat pricing
  PROJECT_STRUCTURE.md
  app/page.tsx
  components/ui/faq.tsx
  components/ui/pricing.tsx
  components/ui/test.tsx
  package-lock.json
  repo_structure.txt
Labels: enhancement, gssoc-ext, level2

#77 Add Mobile-Friendly Sidebar
  PROJECT_STRUCTURE.md
  app/dashboard/_components/Header.tsx
  app/dashboard/_components/MobileSidebar.tsx
  app/dashboard/_components/SideNav.tsx
  app/dashboard/_components/TemplateCard.tsx
  app/dashboard/_components/TemplateListSection.tsx
  app/dashboard/_components/UsageTrack.tsx
  app/dashboard/layout.tsx
  repo_structure.txt
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level3

#76 Create SECURITY.md
  SECURITY.md
Labels: documentation, good first issue, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level1

#79 Review Section Design
  PROJECT_STRUCTURE.md
  app/layout.tsx
  app/page.tsx
  components/ui/review.tsx
  middleware.ts
  package-lock.json
  package.json
  public/Liam.jpg
  public/ava.jpg
  public/james.jpg
  public/sophia.jpg
  public/zara.jpg
  repo_structure.txt
Labels: gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#81 Feat loadingUI
  PROJECT_STRUCTURE.md
  app/page.tsx
  components/ui/loading.tsx
  public/LoadingPage.png
  repo_structure.txt
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level3

#83 Added contributors page
  .env.example
  app/contributors/page.tsx
  components/public-footer.tsx
  package-lock.json
  package.json
  repo_structure.txt
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#82 Deploymentonvercel
  app/(context)/UpdateCreditUsageContext.tsx
  app/dashboard/billing/page.tsx
  app/dashboard/content/[template-slug]/_components/OutputSection.tsx
  app/dashboard/content/[template-slug]/page.tsx
  app/dashboard/history/page.tsx
  app/dashboard/layout.tsx
  app/metadata.tsx
  package-lock.json
  package.json
  utils/schema.tsx
Labels: gssoc-ext, hacktoberfest, level2
