Repository iamkanhaiyakumar/ai-content-generator, pull requests merged in 2024-10, with the labels that each got.

#12 Updated README File ( Issue #4 )
  README.md
Labels: documentation, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level1

#13 Added Templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/greetings.yml
Labels: documentation, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#21 "Added instructions for setting up NeonDB and Clerk in README.md Also added a env.example file for environment variables"
  .env.example
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted, level1

#22 multistaged docker file added
  Dockerfile
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#18 added transitions and effects to the buttons
  components/ui/button.tsx
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#32 Automated project structure updation using github workflows, python scripts and action bot
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  PROJECT_STRUCTURE.md
  README.md
  repo_structure.txt
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level3

#34 added chatbot for enhanced user experience
  app/layout.tsx
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#48 Fixed : Labeler Workflow
  .github/workflows/auto-label.yml
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#46 Added new ai tools
  app/(data)/Template.tsx
  next.config.mjs
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#44 Done the enhancements and also added some new sections
  CONTRIBUTING .md
Labels: documentation, gssoc-ext, hacktoberfest, level1

#51 Add new AI tools to the app/(data)/Template.tsx file
  app/(data)/Template.tsx
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#52 cold mail | resume tailoring tools | cover letter | fixed chatbot related errors
  app/(data)/Template.tsx
  app/dashboard/layout.tsx
  components/ui/Chatbot.tsx
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#57 Notify Contributors When PR Are Merged
  .github/workflows/Auto-comment_on_pr_merge.yml
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#54 🚀 Automate Connections with GitHub Actions!
  .github/workflows/greetings.yml
  .github/workflows/issue_close_open.yml
  .github/workflows/pr_merged.yaml
  .github/workflows/pr_raise.yml
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#61 Middleware Setup for User Authentication Redirection
  .env.example
  PROJECT_STRUCTURE.md
  app/dashboard/_components/Header.tsx
  middleware.ts
  repo_structure.txt
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, level3

#63 created pr checker automation workflow
  .github/workflows/pr-request.yml
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level1

#65 Error 404 page design
  app/not-found.tsx
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#66 Navbar Redesign
  components/public-header.tsx
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#67 Feat FAQ design
  .gitignore
  PROJECT_STRUCTURE.md
  app/page.tsx
  components/ui/faq.tsx
  package-lock.json
  package.json
  repo_structure.txt
  tsconfig.json
Labels: enhancement, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2
